### ISSUE TITLE
Add a splash Screen 

### ISSUE THREAD

**Issue by saifulazad** [saifulazad/Bluetooth-Smart-Home#4]
Add a splash Screen 
http://www.wanhao3dprinter.com/news/UploadFiles_5150/201411/20141106090912202.jpg

**Comment by blackHackers** [comment]
Done!!!

**Comment by sayem405** [comment]
According to expert google developers ..if there is no significant data loading time we should not use Splash Screen. If splash is needed for app branding then they provided a alternative implementation.

please see this : android:theme=https://github.com/sayem405/AppBrandingDemo

**Comment by saifulazad** [comment]
Tnx Sayem for ur review. We will consider this
